/*
frontend/app.js
双节点轮播（上下布局），每个节点显示：时域波形、频谱图、幅度分布直方图和统计信息（RMS、峰值、主频）。
Dual node carousel (top and bottom layout), with each node displaying: time-domain waveform, 
spectrogram, amplitude distribution histogram, and statistical information (RMS, peak, main frequency).
支持自动轮播和手动切换，轮播时间可调。数据通过 WebSocket 实时更新。提供节点类型切换、反色模式和语言切换功能。
Supports automatic rotation and manual switching, with adjustable rotation time. 
The data is updated in real-time through WebSocket. Provide node type switching, color reversal mode, 
and language switching func
支持左键修改节点名称（永久保存至 localStorage）。
Support left clicking to modify node names (permanently saved to localStorage).
支持动态节点数量：通过“节点数量”设置后端生成的节点总数，轮播自动适应。奇数节点时最后一页第二个卡片为空（只显示坐标轴）。
Support for dynamic node count: Set the total number of nodes generated by the backend through "node count", 
and the carousel will automatically adapt. When there are odd nodes, the second card on the last page is empty (only the coordinate axis is displayed).

*/

// ==================== 配置和全局变量 Configuration and global variables====================
let NODE_COUNT = 20;                    // 动态节点数量，初始20/Number of dynamic nodes, initial 20
let PAIR_DURATION = 10000;              // 默认10秒/initial 10s
let currentPairIndex = 0;               // 当前显示的对索引（0-based）/The current pair index (0-based)
let autoPlay = true;
let timer = null;
let countdownInterval = null;

// WebSocket 连接/WebSocket connection
const ws = new WebSocket("ws://" + location.host + "/ws");
// 使用后端原始英文值/Use backend raw English values
let currentNodeType = 'Simulated Data (Generated)';

// 语言配置/language configuration
let currentLang = 'zh';
const translations = {
    zh: {
        pageTitle: '多通道信号实时可视化系统',
        mainTitle: '多通道信号实时可视化系统',
        dataSourceLabel: '数据来源：',
        switchNodeBtn: '更换节点',
        currentDisplayLabel: '当前显示：',
        intervalLabel: '轮询时间：',
        nodeCountLabel: '节点数量：',
        setNodeCountBtn: '设置',
        saveBtn: '保存',
        playPause: { playing: '暂停', paused: '播放' },
        navPrevTitle: '上一对节点',
        navNextTitle: '下一对节点',
        playPauseTitle: '暂停自动轮播',
        timeTitle: '原始信号波形',
        freqTitle: '频域分析',
        histTitle: '信号分布',
        modalTitle: '选择数据节点',
        modalSim: '模拟数据节点（代码生成）',
        modalReal: '真实数据节点',
        modalCancel: '取消',
        statRMS: 'RMS:',
        statPeak: '峰值:',
        statFreq: '频率:',
        unitHz: ' Hz',
        tooltipPrefixTime: '采样点',
        tooltipPrefixFreq: '频率',
        tooltipPrefixHist: '幅度',
        countLabel: '计数',
        countdownSuffix: ' s',
        invertTitle: '切换反色模式',
        langTitle: '切换语言',
        renamePromptPrefix: '请输入节点 ',
        renamePromptSuffix: ' 的新名称:',
        renameTitle: '左键修改节点名称',
        dataSourceSim: '模拟数据节点（代码生成）',
        dataSourceReal: '真实数据节点',
        axisLabels: {
            time: { x: '采样点', y: '幅度' },
            freq: { x: '频率', y: '幅度' },
            hist: { x: '幅度值', y: '频次占比' }
        }
    },
    en: {
        pageTitle: 'SignalScope',
        mainTitle: 'SignalScope',
        dataSourceLabel: 'Data Source: ',
        switchNodeBtn: 'Switch Source',
        currentDisplayLabel: 'Current: ',
        intervalLabel: 'Interval: ',
        nodeCountLabel: 'Nodes: ',
        setNodeCountBtn: 'Set',
        saveBtn: 'Save',
        playPause: { playing: 'Pause', paused: 'Play' },
        navPrevTitle: 'Previous Pair',
        navNextTitle: 'Next Pair',
        playPauseTitle: 'Toggle Auto Play',
        timeTitle: 'Time Domain',
        freqTitle: 'Frequency Domain',
        histTitle: 'Amplitude Distribution',
        modalTitle: 'Select Data Source',
        modalSim: 'Simulated Data (Generated)',
        modalReal: 'Real Data',
        modalCancel: 'Cancel',
        statRMS: 'RMS:',
        statPeak: 'Peak:',
        statFreq: 'Freq:',
        unitHz: ' Hz',
        tooltipPrefixTime: 'Sample',
        tooltipPrefixFreq: 'Freq',
        tooltipPrefixHist: 'Amplitude',
        countLabel: 'Count',
        countdownSuffix: ' s',
        invertTitle: 'Toggle Invert Mode',
        langTitle: 'Switch Language',
        renamePromptPrefix: 'Enter new name for Node ',
        renamePromptSuffix: ':',
        renameTitle: 'Click to rename',
        dataSourceSim: 'Simulated Data (Generated)',
        dataSourceReal: 'Real Data',
        axisLabels: {
            time: { x: 'Sample', y: 'Amplitude' },
            freq: { x: 'Frequency', y: 'Amplitude' },
            hist: { x: 'Amplitude', y: 'Percentage' }
        }
    }
};

// DOM 元素/DOM Elements
const pairLabelSpan = document.getElementById('currentPairLabel');
const countdownSpan = document.getElementById('countdown');
const prevBtn = document.getElementById('prevPairBtn');
const nextBtn = document.getElementById('nextPairBtn');
const playPauseBtn = document.getElementById('playPauseBtn');
const intervalInput = document.getElementById('intervalInput');
const saveIntervalBtn = document.getElementById('saveIntervalBtn');
const nodeCountInput = document.getElementById('nodeCountInput');
const setNodeCountBtn = document.getElementById('setNodeCountBtn');
const currentNodeSpan = document.getElementById('currentNode');

// 画布元素/Canvas Elements
const timeCanvas1 = document.getElementById('timeCanvas1');
const freqCanvas1 = document.getElementById('freqCanvas1');
const histCanvas1 = document.getElementById('histCanvas1');
const timeCanvas2 = document.getElementById('timeCanvas2');
const freqCanvas2 = document.getElementById('freqCanvas2');
const histCanvas2 = document.getElementById('histCanvas2');

// 统计信息元素/Statistical information Elements
const rmsSpan1 = document.getElementById('rms1');
const peakSpan1 = document.getElementById('peak1');
const freqSpan1 = document.getElementById('freq1');
const rmsSpan2 = document.getElementById('rms2');
const peakSpan2 = document.getElementById('peak2');
const freqSpan2 = document.getElementById('freq2');

const nodeNameSpan1 = document.getElementById('nodeName1');
const nodeNameSpan2 = document.getElementById('nodeName2');

// 动态文本元素/Dynamic Text Elements
const pageTitle = document.getElementById('pageTitle');
const mainTitle = document.getElementById('mainTitle');
const dataSourceLabel = document.getElementById('dataSourceLabel');
const switchNodeBtn = document.getElementById('switchNodeBtn');
const currentDisplayLabel = document.getElementById('currentDisplayLabel');
const intervalLabel = document.getElementById('intervalLabel');
const nodeCountLabel = document.getElementById('nodeCountLabel');
const setNodeCountBtnEl = document.getElementById('setNodeCountBtn');
const saveIntervalBtnEl = document.getElementById('saveIntervalBtn');
const timeTitle1 = document.getElementById('timeTitle1');
const freqTitle1 = document.getElementById('freqTitle1');
const histTitle1 = document.getElementById('histTitle1');
const timeTitle2 = document.getElementById('timeTitle2');
const freqTitle2 = document.getElementById('freqTitle2');
const histTitle2 = document.getElementById('histTitle2');
const modalTitle = document.getElementById('modalTitle');
const optSim = document.getElementById('opt-sim');
const optG03 = document.getElementById('opt-g03');
const modalCloseBtn = document.getElementById('modalCloseBtn');

// AXIS 配置（基础结构，label 会在语言切换时动态更新）
// AXIS configuration (infrastructure, labels will be dynamically updated when switching languages)
let AXIS_CONFIG = {
    time: {
        x: { min: 0, max: 400, ticks: [0,100,200,300,400], unit: '×10³', label: '' },
        y: { min: -100, max: 100, ticks: [-100,-50,0,50,100], unit: '', label: '' }
    },
    freq: {
        x: { min: 0, max: 400, ticks: [0,50,100,150,200,250,300,350,400], unit: '', label: '' },
        y: { min: 0, max: 120, ticks: [0,30,60,90,120], unit: 'dB', label: '' }
    },
    hist: {
        x: { min: -100, max: 100, ticks: [-100,-50,0,50,100], unit: '', label: '' },
        y: { min: 0, max: 100, ticks: [0,25,50,75,100], unit: '%', label: '' }
    }
};

function updateAxisLabels() {
    const t = translations[currentLang].axisLabels;
    AXIS_CONFIG.time.x.label = t.time.x;
    AXIS_CONFIG.time.y.label = t.time.y;
    AXIS_CONFIG.freq.x.label = t.freq.x;
    AXIS_CONFIG.freq.y.label = t.freq.y;
    AXIS_CONFIG.hist.x.label = t.hist.x;
    AXIS_CONFIG.hist.y.label = t.hist.y;
}

const margin = { left: 60, right: 25, top: 24, bottom: 45 };
const tooltip = document.getElementById('tooltip');

// ==================== 辅助函数：总对数 ====================
function getTotalPairs() {
    return Math.ceil(NODE_COUNT / 2);
}

// ==================== 保存和加载设置 Save and load settings====================
function loadSettings() {
    const savedInterval = localStorage.getItem('signalScopeInterval');
    if (savedInterval) {
        let sec = parseInt(savedInterval, 10);
        if (!isNaN(sec) && sec >= 1 && sec <= 60) {
            PAIR_DURATION = sec * 1000;
            intervalInput.value = sec;
        }
    }
    const savedNodeCount = localStorage.getItem('signalScopeNodeCount');
    if (savedNodeCount) {
        let cnt = parseInt(savedNodeCount, 10);
        if (!isNaN(cnt) && cnt >= 1 && cnt <= 100) {
            NODE_COUNT = cnt;
            nodeCountInput.value = cnt;
            if (ws.readyState === WebSocket.OPEN) {
                ws.send(JSON.stringify({ action: 'set_node_count', count: cnt }));
            }
        }
    }
}

function saveIntervalSetting() {
    localStorage.setItem('signalScopeInterval', intervalInput.value);
}

function saveNodeCountSetting() {
    localStorage.setItem('signalScopeNodeCount', nodeCountInput.value);
}

// ==================== 语言切换Language switch ====================
function updateUILanguage() {
    const t = translations[currentLang];
    pageTitle.innerText = t.pageTitle;
    mainTitle.innerText = t.mainTitle;
    dataSourceLabel.innerText = t.dataSourceLabel;
    switchNodeBtn.innerText = t.switchNodeBtn;
    currentDisplayLabel.innerText = t.currentDisplayLabel;
    intervalLabel.innerText = t.intervalLabel;
    nodeCountLabel.innerText = t.nodeCountLabel;
    setNodeCountBtnEl.innerText = t.setNodeCountBtn;
    saveIntervalBtnEl.innerText = t.saveBtn;
    timeTitle1.innerText = t.timeTitle;
    freqTitle1.innerText = t.freqTitle;
    histTitle1.innerText = t.histTitle;
    timeTitle2.innerText = t.timeTitle;
    freqTitle2.innerText = t.freqTitle;
    histTitle2.innerText = t.histTitle;
    modalTitle.innerText = t.modalTitle;
    optSim.innerHTML = t.modalSim + '<small></small>';
    optG03.innerHTML = t.modalReal + '<small></small>';
    modalCloseBtn.innerText = t.modalCancel;
    
    const statLabels = document.querySelectorAll('.stat-label');
    if (statLabels.length >= 6) {
        statLabels[0].innerText = t.statRMS;
        statLabels[1].innerText = t.statPeak;
        statLabels[2].innerText = t.statFreq;
        statLabels[3].innerText = t.statRMS;
        statLabels[4].innerText = t.statPeak;
        statLabels[5].innerText = t.statFreq;
    }
    prevBtn.title = t.navPrevTitle;
    nextBtn.title = t.navNextTitle;
    playPauseBtn.title = t.playPauseTitle;
    invertBtn.title = t.invertTitle;
    langSwitchBtn.title = t.langTitle;
    langSwitchBtn.innerText = currentLang === 'zh' ? 'Ch' : 'EN';
    
    nodeNameSpan1.title = t.renameTitle;
    nodeNameSpan2.title = t.renameTitle;
    
    updateAxisLabels();
    updateCurrentNodeDisplay();
    
    const countdownText = countdownSpan.innerText;
    const numMatch = countdownText.match(/[\d.]+/);
    if (numMatch && countdownText !== '-- s') {
        countdownSpan.innerText = numMatch[0] + t.countdownSuffix;
    } else if (countdownText === '-- s') {
        countdownSpan.innerText = '--' + t.countdownSuffix;
    }
    if (autoPlay) {
        playPauseBtn.innerText = t.playPause.playing;
    } else {
        playPauseBtn.innerText = t.playPause.paused;
    }
    updatePairLabel();
    if (latestNodesData) {
        updateDisplayedNodes(latestNodesData);
    } else {
        resizeAllCanvases();
        redrawEmptyCanvases();
    }
}

function redrawEmptyCanvases() {
    const allCanvases = [timeCanvas1, freqCanvas1, histCanvas1, timeCanvas2, freqCanvas2, histCanvas2];
    allCanvases.forEach(canvas => {
        if (canvas && canvas.getContext) {
            const ctx = canvas.getContext('2d');
            const w = canvas.width / (canvas.dpr || 1);
            const h = canvas.height / (canvas.dpr || 1);
            ctx.clearRect(0, 0, w, h);
            ctx.fillStyle = "white";
            ctx.fillRect(0, 0, w, h);
        }
    });
}


function updateCurrentNodeDisplay() {
    const t = translations[currentLang];
    if (currentNodeType === 'Simulated Data (Generated)') {
        currentNodeSpan.innerText = t.dataSourceSim;
    } else if (currentNodeType === 'Real Data (Hardware)') {
        currentNodeSpan.innerText = t.dataSourceReal;
    } else {
        currentNodeSpan.innerText = currentNodeType;
    }
}

function toggleLanguage() {
    currentLang = currentLang === 'zh' ? 'en' : 'zh';
    updateUILanguage();
    localStorage.setItem('signalScopeLang', currentLang);
}

// ==================== 节点名称存储与辅助函数 Node name storage and auxiliary functions====================
function loadNodeNames() {
    const stored = localStorage.getItem('signalScopeNodeNames');
    if (stored) {
        try {
            return JSON.parse(stored);
        } catch(e) { return {}; }
    }
    return {};
}

function saveNodeNames(namesMap) {
    localStorage.setItem('signalScopeNodeNames', JSON.stringify(namesMap));
}

function getNodeDisplayName(nodeNumber) {
    const names = loadNodeNames();
    if (names[nodeNumber]) {
        return names[nodeNumber];
    }
    const t = translations[currentLang];
    return currentLang === 'zh' ? `节点 ${nodeNumber}` : `Node ${nodeNumber}`;
}

function setNodeName(nodeNumber, customName) {
    if (!customName || customName.trim() === "") return;
    const names = loadNodeNames();
    names[nodeNumber] = customName.trim();
    saveNodeNames(names);
    const idx1 = currentPairIndex * 2 + 1;
    const idx2 = currentPairIndex * 2 + 2;
    if (nodeNumber === idx1) nodeNameSpan1.innerText = customName.trim();
    if (nodeNumber === idx2 && idx2 <= NODE_COUNT) nodeNameSpan2.innerText = customName.trim();
    updatePairLabel();
}

// ==================== 辅助函数 auxiliary functions====================
function updatePairLabel() {
    const idx1 = currentPairIndex * 2 + 1;
    const idx2 = currentPairIndex * 2 + 2;
    const t = translations[currentLang];
    const prefix = currentLang === 'zh' ? '节点 ' : 'Node ';
    if (idx2 <= NODE_COUNT) {
        pairLabelSpan.innerText = `${prefix}${idx1} & ${prefix}${idx2}`;
    } else {
        pairLabelSpan.innerText = `${prefix}${idx1}`;
    }
    nodeNameSpan1.innerText = getNodeDisplayName(idx1);
    if (idx2 <= NODE_COUNT) {
        nodeNameSpan2.innerText = getNodeDisplayName(idx2);
    } else {
        nodeNameSpan2.innerText = getNodeDisplayName(idx2);
    }
}

function switchToPairByIndex(pairIndex) {
    const totalPairs = getTotalPairs();
    if (totalPairs === 0) return;
    pairIndex = (pairIndex + totalPairs) % totalPairs;
    currentPairIndex = pairIndex;
    updatePairLabel();
    resetCountdownDisplay();
    if (latestNodesData) {
        updateDisplayedNodes(latestNodesData);
    }
}

function nextPair() {
    const nextIndex = (currentPairIndex + 1) % getTotalPairs();
    switchToPairByIndex(nextIndex);
    resetAutoTimer();
}

function prevPair() {
    const total = getTotalPairs();
    const prevIndex = (currentPairIndex - 1 + total) % total;
    switchToPairByIndex(prevIndex);
    resetAutoTimer();
}

function resetAutoTimer() {
    if (timer) clearTimeout(timer);
    if (autoPlay) {
        timer = setTimeout(() => {
            nextPair();
        }, PAIR_DURATION);
    }
    startCountdown();
}

function startCountdown() {
    if (countdownInterval) clearInterval(countdownInterval);
    if (!autoPlay) {
        countdownSpan.innerText = '--' + translations[currentLang].countdownSuffix;
        return;
    }
    let remaining = Math.ceil(PAIR_DURATION / 1000);
    countdownSpan.innerText = `${remaining}${translations[currentLang].countdownSuffix}`;
    countdownInterval = setInterval(() => {
        if (!autoPlay) {
            if (countdownInterval) clearInterval(countdownInterval);
            return;
        }
        remaining -= 1;
        if (remaining <= 0) {
            clearInterval(countdownInterval);
            countdownSpan.innerText = `0${translations[currentLang].countdownSuffix}`;
        } else {
            countdownSpan.innerText = `${remaining}${translations[currentLang].countdownSuffix}`;
        }
    }, 1000);
}

function resetCountdownDisplay() {
    if (countdownInterval) clearInterval(countdownInterval);
    if (autoPlay) {
        startCountdown();
    } else {
        countdownSpan.innerText = '--' + translations[currentLang].countdownSuffix;
    }
}

function toggleAutoPlay() {
    autoPlay = !autoPlay;
    const t = translations[currentLang];
    if (autoPlay) {
        playPauseBtn.innerText = t.playPause.playing;
        playPauseBtn.classList.remove('paused');
        resetAutoTimer();
    } else {
        playPauseBtn.innerText = t.playPause.paused;
        playPauseBtn.classList.add('paused');
        if (timer) clearTimeout(timer);
        if (countdownInterval) clearInterval(countdownInterval);
        countdownSpan.innerText = '--' + t.countdownSuffix;
    }
}

function saveInterval() {
    let newSeconds = parseInt(intervalInput.value, 10);
    if (isNaN(newSeconds)) newSeconds = 10;
    newSeconds = Math.min(60, Math.max(1, newSeconds));
    intervalInput.value = newSeconds;
    PAIR_DURATION = newSeconds * 1000;
    saveIntervalSetting();
    if (autoPlay) {
        resetAutoTimer();
    } else {
        if (timer) clearTimeout(timer);
        if (countdownInterval) clearInterval(countdownInterval);
        countdownSpan.innerText = '--' + translations[currentLang].countdownSuffix;
    }
}

function setNodeCount(newCount) {
    if (newCount === NODE_COUNT) return;
    if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ action: 'set_node_count', count: newCount }));
    } else {
        console.warn('WebSocket not open');
    }
    saveNodeCountSetting();
}

// ==================== HiDPI 自适应画布设置 HiDPI adaptive canvas settings====================
function setupHiDPICanvas(canvas) {
    const container = canvas.parentElement;
    if (!container) return null;
    const rect = container.getBoundingClientRect();
    let width = rect.width;
    let height = rect.height;
    if (width <= 0 || height <= 0) {
        width = 300;
        height = 200;
    }
    const dpr = window.devicePixelRatio || 1;
    canvas.style.width = width + 'px';
    canvas.style.height = height + 'px';
    canvas.width = Math.floor(width * dpr);
    canvas.height = Math.floor(height * dpr);
    const ctx = canvas.getContext('2d');
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.scale(dpr, dpr);
    canvas.dpr = dpr;
    canvas.logicalWidth = width;
    canvas.logicalHeight = height;
    return ctx;
}

function resizeAllCanvases() {
    const canvases = [timeCanvas1, freqCanvas1, histCanvas1, timeCanvas2, freqCanvas2, histCanvas2];
    canvases.forEach(c => { if (c) setupHiDPICanvas(c); });
}

// ==================== 绘图函数 plotting function====================
function drawFixedAxes(ctx, config) {
    const canvas = ctx.canvas;
    const dpr = canvas.dpr || 1;
    const width = canvas.logicalWidth || (canvas.width / dpr);
    const height = canvas.logicalHeight || (canvas.height / dpr);
    const plotWidth = width - margin.left - margin.right;
    const plotHeight = height - margin.top - margin.bottom;

    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, width, height);

    ctx.strokeStyle = "#000";
    ctx.lineWidth = 1.2;
    ctx.fillStyle = "#000";

    const left = Math.floor(margin.left);
    const top = Math.floor(margin.top);
    const right = Math.floor(width - margin.right);
    const bottom = Math.floor(height - margin.bottom);

    ctx.strokeRect(left, top, right - left, bottom - top);
    ctx.font = "12px Arial, sans-serif";
    ctx.fillStyle = "#000";
    ctx.textAlign = "center";
    ctx.textBaseline = "top";

    config.x.ticks.forEach(tick => {
        const x = Math.floor(left + (tick - config.x.min) / (config.x.max - config.x.min) * plotWidth);
        ctx.beginPath();
        ctx.moveTo(x, bottom);
        ctx.lineTo(x, bottom + 5);
        ctx.stroke();
        const labelY = bottom + 8;
        if (labelY < height - 5) ctx.fillText(tick.toString(), x, labelY);
        if (tick !== config.x.min && tick !== config.x.max) {
            ctx.strokeStyle = "#e0e0e0";
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.moveTo(x, top);
            ctx.lineTo(x, bottom);
            ctx.stroke();
            ctx.strokeStyle = "#000";
            ctx.lineWidth = 1.2;
        }
    });

    ctx.font = "bold 13px 'Microsoft YaHei', SimHei, sans-serif";
    const xLabelText = config.x.label + (config.x.unit ? ` (${config.x.unit})` : '');
    const xLabelY = bottom + 25;
    if (xLabelY < height - 2) ctx.fillText(xLabelText, width / 2, xLabelY);

    ctx.textAlign = "right";
    ctx.textBaseline = "middle";
    ctx.font = "12px Arial, sans-serif";
    config.y.ticks.forEach(tick => {
        const y = Math.floor(bottom - (tick - config.y.min) / (config.y.max - config.y.min) * plotHeight);
        ctx.beginPath();
        ctx.moveTo(left - 5, y);
        ctx.lineTo(left, y);
        ctx.stroke();
        ctx.fillText(tick.toString(), left - 8, y);
        if (tick !== config.y.min && tick !== config.y.max) {
            ctx.strokeStyle = "#e0e0e0";
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.moveTo(left, y);
            ctx.lineTo(right, y);
            ctx.stroke();
            ctx.strokeStyle = "#000";
            ctx.lineWidth = 1.2;
        }
    });

    ctx.save();
    ctx.translate(20, height / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.font = "bold 13px 'Microsoft YaHei', SimHei, sans-serif";
    const yLabelText = config.y.label + (config.y.unit ? ` (${config.y.unit})` : '');
    ctx.fillText(yLabelText, 0, 0);
    ctx.restore();
}

function drawLinePlot(canvas, data, color, config) {
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const dpr = canvas.dpr || 1;
    const width = canvas.width / dpr;
    const height = canvas.height / dpr;
    const plotWidth = width - margin.left - margin.right;
    const plotHeight = height - margin.top - margin.bottom;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, width, height);
    drawFixedAxes(ctx, config);
    if (data && data.length > 0) {
        ctx.beginPath();
        ctx.strokeStyle = color;
        ctx.lineWidth = 1.8;
        const points = [];
        const n = data.length;
        for (let i = 0; i < n; i++) {
            const xVal = config.x.min + (i / (n - 1)) * (config.x.max - config.x.min);
            const x = margin.left + (xVal - config.x.min) / (config.x.max - config.x.min) * plotWidth;
            const y = height - margin.bottom - (data[i] - config.y.min) / (config.y.max - config.y.min) * plotHeight;
            points.push({ x, y, val: data[i], xVal, index: i });
            if (i === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.stroke();
        canvas.config = config;
        canvas.dataPoints = points;
    } else {
        canvas.config = config;
        canvas.dataPoints = [];
    }
}

function drawHistogram(canvas, data, config) {
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const dpr = canvas.dpr || 1;
    const width = canvas.width / dpr;
    const height = canvas.height / dpr;
    const plotWidth = width - margin.left - margin.right;
    const plotHeight = height - margin.top - margin.bottom;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, width, height);
    drawFixedAxes(ctx, config);
    if (data && data.length > 0) {
        const bins = 50;
        const binWidth = (config.x.max - config.x.min) / bins;
        const counts = new Array(bins).fill(0);
        data.forEach(val => {
            if (val >= config.x.min && val <= config.x.max) {
                const idx = Math.min(Math.floor((val - config.x.min) / binWidth), bins - 1);
                counts[idx]++;
            }
        });
        const maxCount = Math.max(...counts) || 1;
        const barWidth = plotWidth / bins;
        ctx.fillStyle = "steelblue";
        const bars = [];
        counts.forEach((count, i) => {
            const pct = (count / maxCount) * 100;
            const h = (pct / 100) * plotHeight;
            const x = margin.left + i * barWidth;
            const y = height - margin.bottom - h;
            if (h > 0.5) {
                ctx.fillRect(x + 1, y, barWidth - 2, h);
                bars.push({
                    x1: x + 1, x2: x + barWidth - 2, y1: y, y2: height - margin.bottom,
                    count: count, percentage: pct.toFixed(1), xVal: config.x.min + (i + 0.5) * binWidth
                });
            }
        });
        canvas.histBars = bars;
    } else {
        canvas.histBars = [];
    }
    canvas.config = config;
}

function setupMouseInteraction(canvas, isHistogram = false) {
    if (!canvas) return;
    canvas.addEventListener('click', function(e) {
        const rect = canvas.getBoundingClientRect();
        const config = canvas.config;
        if (!config) return;
        const logicalX = (e.clientX - rect.left) * (canvas.width / rect.width) / (canvas.dpr || 1);
        const logicalY = (e.clientY - rect.top) * (canvas.height / rect.height) / (canvas.dpr || 1);
        let displayText = '';
        let found = false;
        if (isHistogram) {
            const bars = canvas.histBars || [];
            const t = translations[currentLang];
            for (let bar of bars) {
                if (logicalX >= bar.x1 && logicalX <= bar.x2 && logicalY >= bar.y1 && logicalY <= bar.y2) {
                    displayText = `${t.tooltipPrefixHist}: ${bar.xVal.toFixed(1)}  ${t.countLabel}: ${bar.count} (${bar.percentage}%)`;
                    found = true;
                    break;
                }
            }
        } else {
            const points = canvas.dataPoints || [];
            if (points.length) {
                const plotLeft = margin.left;
                const plotWidth = (canvas.width / (canvas.dpr || 1)) - margin.left - margin.right;
                const xVal = config.x.min + (logicalX - plotLeft) / plotWidth * (config.x.max - config.x.min);
                const dataIndex = Math.round((xVal - config.x.min) / (config.x.max - config.x.min) * (points.length - 1));
                if (dataIndex >= 0 && dataIndex < points.length) {
                    const point = points[dataIndex];
                    const dist = Math.hypot(logicalX - point.x, logicalY - point.y);
                    if (dist < 12) {
                        const prefix = (config === AXIS_CONFIG.time) ? translations[currentLang].tooltipPrefixTime : translations[currentLang].tooltipPrefixFreq;
                        displayText = `${prefix}: ${point.xVal.toFixed(1)}  ${config.y.label}: ${point.val.toFixed(1)}${config.y.unit}`;
                        found = true;
                    }
                }
            }
        }
        if (found) {
            tooltip.textContent = displayText;
            tooltip.style.display = 'block';
            tooltip.style.left = (e.clientX + 8) + 'px';
            tooltip.style.top = (e.clientY - 28) + 'px';
            setTimeout(() => tooltip.style.display = 'none', 3000);
        } else {
            tooltip.style.display = 'none';
        }
    });
}

// ==================== 更新当前显示的两个节点 Update the two nodes currently displayed====================
let latestNodesData = null;

function updateDisplayedNodes(nodesArray) {
    if (!nodesArray) return;
    const node1Index = currentPairIndex * 2;
    const node2Index = currentPairIndex * 2 + 1;
    const node1 = nodesArray[node1Index] || null;
    const node2 = (node2Index < NODE_COUNT) ? nodesArray[node2Index] : null;

    if (node1) {
        drawLinePlot(timeCanvas1, node1.samples || [], "#1f77b4", AXIS_CONFIG.time);
        drawLinePlot(freqCanvas1, node1.spectrum || [], "#2ca02c", AXIS_CONFIG.freq);
        drawHistogram(histCanvas1, node1.samples || [], AXIS_CONFIG.hist);
        rmsSpan1.innerText = (node1.rms || 0).toFixed(2);
        peakSpan1.innerText = (node1.peak || 0).toFixed(2);
        freqSpan1.innerText = (node1.peakFreq || 0).toFixed(1) + translations[currentLang].unitHz;
    } else {
        drawLinePlot(timeCanvas1, [], "#1f77b4", AXIS_CONFIG.time);
        drawLinePlot(freqCanvas1, [], "#2ca02c", AXIS_CONFIG.freq);
        drawHistogram(histCanvas1, [], AXIS_CONFIG.hist);
        rmsSpan1.innerText = "0.00";
        peakSpan1.innerText = "0.00";
        freqSpan1.innerText = "0.0" + translations[currentLang].unitHz;
    }

    if (node2) {
        drawLinePlot(timeCanvas2, node2.samples || [], "#1f77b4", AXIS_CONFIG.time);
        drawLinePlot(freqCanvas2, node2.spectrum || [], "#2ca02c", AXIS_CONFIG.freq);
        drawHistogram(histCanvas2, node2.samples || [], AXIS_CONFIG.hist);
        rmsSpan2.innerText = (node2.rms || 0).toFixed(2);
        peakSpan2.innerText = (node2.peak || 0).toFixed(2);
        freqSpan2.innerText = (node2.peakFreq || 0).toFixed(1) + translations[currentLang].unitHz;
    } else {
        drawLinePlot(timeCanvas2, [], "#1f77b4", AXIS_CONFIG.time);
        drawLinePlot(freqCanvas2, [], "#2ca02c", AXIS_CONFIG.freq);
        drawHistogram(histCanvas2, [], AXIS_CONFIG.hist);
        rmsSpan2.innerText = "0.00";
        peakSpan2.innerText = "0.00";
        freqSpan2.innerText = "0.0" + translations[currentLang].unitHz;
    }
}

// ==================== WebSocket 事件处理 WebSocket event handling====================
ws.onmessage = function(event) {
    const d = JSON.parse(event.data);
    if (Array.isArray(d.nodes)) {
        const newCount = d.nodes.length;
        if (newCount !== NODE_COUNT) {
            NODE_COUNT = newCount;
            nodeCountInput.value = NODE_COUNT;
            saveNodeCountSetting();
            currentPairIndex = 0;
            updatePairLabel();
            if (latestNodesData) {
                updateDisplayedNodes(latestNodesData);
            }
        }
        latestNodesData = d.nodes;
        updateDisplayedNodes(latestNodesData);
    }
    if (d.current_node) {
        currentNodeType = d.current_node;
        updateCurrentNodeDisplay();
    }
};

ws.onopen = function() {
    console.log('WebSocket 连接已建立');
    ws.send(JSON.stringify({ action: 'switch_node', node: currentNodeType }));
    if (NODE_COUNT !== 20) {
        ws.send(JSON.stringify({ action: 'set_node_count', count: NODE_COUNT }));
    }
};

ws.onerror = (error) => console.error("WebSocket 错误:", error);
ws.onclose = () => console.log("WebSocket 连接已关闭");

// ==================== 节点类型切换 Point type switching====================
function showNodeSelector() {
    document.getElementById('nodeModal').style.display = 'block';
    if (currentNodeType === 'Simulated Data (Generated)') {
        optSim.classList.add('active');
        optG03.classList.remove('active');
    } else {
        optG03.classList.add('active');
        optSim.classList.remove('active');
    }
}

function closeModal() {
    document.getElementById('nodeModal').style.display = 'none';
}

function selectNode(nodeName) {
    currentNodeType = nodeName;
    updateCurrentNodeDisplay();
    closeModal();
    if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ action: 'switch_node', node: currentNodeType }));
    }
}

window.onclick = function(event) {
    const modal = document.getElementById('nodeModal');
    if (event.target === modal) closeModal();
};

// ==================== 反色模式切换 Color reversal mode switching====================
const invertBtn = document.getElementById('invertModeBtn');
function initInvertMode() {
    const body = document.body;
    const isInverted = localStorage.getItem('invertMode') === 'true';
    if (isInverted) {
        body.classList.add('inverted');
        invertBtn.textContent = '☀';
    } else {
        body.classList.remove('inverted');
        invertBtn.textContent = '☾';
    }
    invertBtn.addEventListener('click', () => {
        body.classList.toggle('inverted');
        const nowInverted = body.classList.contains('inverted');
        localStorage.setItem('invertMode', nowInverted);
        invertBtn.textContent = nowInverted ? '☀' : '☾';
        setTimeout(() => {
            if (latestNodesData) updateDisplayedNodes(latestNodesData);
            else resizeAllCanvases();
        }, 50);
    });
}

// ==================== 初始化initialization ====================
document.addEventListener('DOMContentLoaded', function() {
    const canvases = [
        { canvas: timeCanvas1, hist: false },
        { canvas: freqCanvas1, hist: false },
        { canvas: histCanvas1, hist: true },
        { canvas: timeCanvas2, hist: false },
        { canvas: freqCanvas2, hist: false },
        { canvas: histCanvas2, hist: true }
    ];
    canvases.forEach(item => {
        setupHiDPICanvas(item.canvas);
        setupMouseInteraction(item.canvas, item.hist);
    });
    window.addEventListener('resize', () => {
        clearTimeout(window._resizeTimer);
        window._resizeTimer = setTimeout(() => resizeAllCanvases(), 200);
    });

    loadSettings();

    const savedLang = localStorage.getItem('signalScopeLang');
    if (savedLang === 'en' || savedLang === 'zh') {
        currentLang = savedLang;
    } else {
        currentLang = 'zh';
    }
    updateAxisLabels();
    updateUILanguage();

    setNodeCountBtn.addEventListener('click', () => {
        let newCount = parseInt(nodeCountInput.value, 10);
        if (isNaN(newCount)) newCount = 20;
        newCount = Math.min(100, Math.max(1, newCount));
        nodeCountInput.value = newCount;
        setNodeCount(newCount);
    });

    switchToPairByIndex(0);
    prevBtn.addEventListener('click', () => { prevPair(); resetAutoTimer(); });
    nextBtn.addEventListener('click', () => { nextPair(); resetAutoTimer(); });
    playPauseBtn.addEventListener('click', toggleAutoPlay);
    saveIntervalBtn.addEventListener('click', saveInterval);
    resetAutoTimer();
    initInvertMode();

    const langSwitchBtn = document.getElementById('langSwitchBtn');
    langSwitchBtn.addEventListener('click', toggleLanguage);

    function bindRenameClick() {
        const renameHandler = (e, indexOffset) => {
            const nodeNumber = currentPairIndex * 2 + indexOffset + 1;
            if (nodeNumber > NODE_COUNT) return;
            const t = translations[currentLang];
            const currentName = getNodeDisplayName(nodeNumber);
            const newName = prompt(`${t.renamePromptPrefix}${nodeNumber}${t.renamePromptSuffix}`, currentName);
            if (newName && newName.trim() !== "") {
                setNodeName(nodeNumber, newName.trim());
            }
        };
        nodeNameSpan1.addEventListener('click', (e) => renameHandler(e, 0));
        nodeNameSpan2.addEventListener('click', (e) => renameHandler(e, 1));
    }
    bindRenameClick();
});